[package]
name = "backtest-python"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
backtest-core = { path = "../backtest-core" }
numpy.workspace = true
pyo3.workspace = true
